#!/bin/env python3

# MVP usage: blockpy blocktime:unblocktime website

import sys, json, os
from pathlib import Path

path = '/etc/blockpy/'
json_name="blockpy.json"
path_to_json = path+json_name

def load_json():
    if(not os.path.exists(path)):
        os.makedirs(path)
        print("creating /etc/blockpy")
    
    Path(path_to_json).touch(exist_ok=True)
    json_file = open(path_to_json,'r+')
    text = json_file.read()
    if text == "":
        text = "{}"
    json_file.close()
    return json.loads(text)

def write_json_file(text):
    json_file = open(path_to_json,'w')
    json_file.write(text)
    json_file.close()


def main():
    args = sys.argv[1:]
    d = load_json()
    website = args[1]
    if(args[0] == "delete"):
        del d[website]
        out = json.dumps(d)
        write_json_file(out)
        return

    times = args[0].split('-')
    website = args[1]
    blocktime = times[0]
    unblocktime = times[1]


    d[website]= (blocktime,unblocktime)
    out = json.dumps(d)
    write_json_file(out)

euid = os.geteuid()
if(euid != 0):
    print("Please run with privileges")
    exit(2)
main() 